fragment HomepageParts on Homepage {
  __typename
  hero {
    __typename
    title
    subtitle
    videoUrl
  }
  intro {
    __typename
    kicker
    title
    body
  }
  selectedProjects {
    __typename
    project {
      ... on Projects {
        __typename
        title
        slug
        client
        industry
        year
        services
        excerpt
        heroImage
        published
        order
        blocks {
          __typename
          ... on ProjectsBlocksHeroOverride {
            title
            image
          }
          ... on ProjectsBlocksFullImage {
            image
            caption
          }
          ... on ProjectsBlocksTextBlock {
            heading
            body
          }
          ... on ProjectsBlocksTwoColumn {
            leftContent
            rightImage
          }
          ... on ProjectsBlocksGallery {
            images
          }
          ... on ProjectsBlocksQuote {
            quoteText
            author
          }
          ... on ProjectsBlocksSpacer {
            size
          }
        }
      }
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
    }
  }
}

fragment ServicesParts on Services {
  __typename
  headline
  intro
  disciplines {
    __typename
    number
    label
    statement
    deliverables
  }
  process {
    __typename
    step
    title
    text
  }
}

fragment AboutParts on About {
  __typename
  headline
  intro
  positioning {
    __typename
    title
    text
  }
}

fragment TeamParts on Team {
  __typename
  members {
    __typename
    name
    title
    image
    shortBio
    fullBio
  }
}

fragment BlogParts on Blog {
  __typename
  title
  slug
  date
  coverImage
  excerpt
  published
  order
  blocks {
    __typename
    ... on BlogBlocksHeroOverride {
      title
      image
    }
    ... on BlogBlocksFullImage {
      image
      caption
    }
    ... on BlogBlocksTextBlock {
      heading
      body
    }
    ... on BlogBlocksTwoColumn {
      leftContent
      rightImage
    }
    ... on BlogBlocksGallery {
      images
    }
    ... on BlogBlocksQuote {
      quoteText
      author
    }
    ... on BlogBlocksSpacer {
      size
    }
  }
}

fragment ProjectsParts on Projects {
  __typename
  title
  slug
  client
  industry
  year
  services
  excerpt
  heroImage
  published
  order
  blocks {
    __typename
    ... on ProjectsBlocksHeroOverride {
      title
      image
    }
    ... on ProjectsBlocksFullImage {
      image
      caption
    }
    ... on ProjectsBlocksTextBlock {
      heading
      body
    }
    ... on ProjectsBlocksTwoColumn {
      leftContent
      rightImage
    }
    ... on ProjectsBlocksGallery {
      images
    }
    ... on ProjectsBlocksQuote {
      quoteText
      author
    }
    ... on ProjectsBlocksSpacer {
      size
    }
  }
}
