//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  services: Services;
  servicesConnection: ServicesConnection;
  about: About;
  aboutConnection: AboutConnection;
  team: Team;
  teamConnection: TeamConnection;
  blog: Blog;
  blogConnection: BlogConnection;
  projects: Projects;
  projectsConnection: ProjectsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryProjectsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
};

export type DocumentFilter = {
  homepage?: InputMaybe<HomepageFilter>;
  services?: InputMaybe<ServicesFilter>;
  about?: InputMaybe<AboutFilter>;
  team?: InputMaybe<TeamFilter>;
  blog?: InputMaybe<BlogFilter>;
  projects?: InputMaybe<ProjectsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Homepage | Services | About | Team | Blog | Projects | Folder;

export type HomepageHero = {
  __typename?: 'HomepageHero';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  videoUrl?: Maybe<Scalars['String']['output']>;
};

export type HomepageIntro = {
  __typename?: 'HomepageIntro';
  kicker?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
};

export type HomepageSelectedProjectsProject = Projects;

export type HomepageSelectedProjects = {
  __typename?: 'HomepageSelectedProjects';
  project?: Maybe<HomepageSelectedProjectsProject>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  hero?: Maybe<HomepageHero>;
  intro?: Maybe<HomepageIntro>;
  selectedProjects?: Maybe<Array<Maybe<HomepageSelectedProjects>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomepageHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomepageIntroFilter = {
  kicker?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type HomepageSelectedProjectsProjectFilter = {
  projects?: InputMaybe<ProjectsFilter>;
};

export type HomepageSelectedProjectsFilter = {
  project?: InputMaybe<HomepageSelectedProjectsProjectFilter>;
};

export type HomepageFilter = {
  hero?: InputMaybe<HomepageHeroFilter>;
  intro?: InputMaybe<HomepageIntroFilter>;
  selectedProjects?: InputMaybe<HomepageSelectedProjectsFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type ServicesDisciplines = {
  __typename?: 'ServicesDisciplines';
  number?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  statement?: Maybe<Scalars['String']['output']>;
  deliverables?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ServicesProcess = {
  __typename?: 'ServicesProcess';
  step?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  headline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  disciplines?: Maybe<Array<Maybe<ServicesDisciplines>>>;
  process?: Maybe<Array<Maybe<ServicesProcess>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesDisciplinesFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  statement?: InputMaybe<StringFilter>;
  deliverables?: InputMaybe<StringFilter>;
};

export type ServicesProcessFilter = {
  step?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type ServicesFilter = {
  headline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  disciplines?: InputMaybe<ServicesDisciplinesFilter>;
  process?: InputMaybe<ServicesProcessFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type AboutPositioning = {
  __typename?: 'AboutPositioning';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type About = Node & Document & {
  __typename?: 'About';
  headline?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  positioning?: Maybe<Array<Maybe<AboutPositioning>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutPositioningFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  headline?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  positioning?: InputMaybe<AboutPositioningFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type TeamMembers = {
  __typename?: 'TeamMembers';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  shortBio?: Maybe<Scalars['String']['output']>;
  fullBio?: Maybe<Scalars['String']['output']>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  members?: Maybe<Array<Maybe<TeamMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TeamMembersFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  shortBio?: InputMaybe<StringFilter>;
  fullBio?: InputMaybe<StringFilter>;
};

export type TeamFilter = {
  members?: InputMaybe<TeamMembersFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type BlogBlocksHeroOverride = {
  __typename?: 'BlogBlocksHeroOverride';
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type BlogBlocksFullImage = {
  __typename?: 'BlogBlocksFullImage';
  image?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type BlogBlocksTextBlock = {
  __typename?: 'BlogBlocksTextBlock';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
};

export type BlogBlocksTwoColumn = {
  __typename?: 'BlogBlocksTwoColumn';
  leftContent?: Maybe<Scalars['JSON']['output']>;
  rightImage?: Maybe<Scalars['String']['output']>;
};

export type BlogBlocksGallery = {
  __typename?: 'BlogBlocksGallery';
  images?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type BlogBlocksQuote = {
  __typename?: 'BlogBlocksQuote';
  quoteText?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
};

export type BlogBlocksSpacer = {
  __typename?: 'BlogBlocksSpacer';
  size?: Maybe<Scalars['String']['output']>;
};

export type BlogBlocks = BlogBlocksHeroOverride | BlogBlocksFullImage | BlogBlocksTextBlock | BlogBlocksTwoColumn | BlogBlocksGallery | BlogBlocksQuote | BlogBlocksSpacer;

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  date: Scalars['String']['output'];
  coverImage: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  published?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  blocks?: Maybe<Array<Maybe<BlogBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BlogBlocksHeroOverrideFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type BlogBlocksFullImageFilter = {
  image?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type BlogBlocksTextBlockFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogBlocksTwoColumnFilter = {
  leftContent?: InputMaybe<RichTextFilter>;
  rightImage?: InputMaybe<ImageFilter>;
};

export type BlogBlocksGalleryFilter = {
  images?: InputMaybe<ImageFilter>;
};

export type BlogBlocksQuoteFilter = {
  quoteText?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
};

export type BlogBlocksSpacerFilter = {
  size?: InputMaybe<StringFilter>;
};

export type BlogBlocksFilter = {
  heroOverride?: InputMaybe<BlogBlocksHeroOverrideFilter>;
  fullImage?: InputMaybe<BlogBlocksFullImageFilter>;
  textBlock?: InputMaybe<BlogBlocksTextBlockFilter>;
  twoColumn?: InputMaybe<BlogBlocksTwoColumnFilter>;
  gallery?: InputMaybe<BlogBlocksGalleryFilter>;
  quote?: InputMaybe<BlogBlocksQuoteFilter>;
  spacer?: InputMaybe<BlogBlocksSpacerFilter>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  excerpt?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
  blocks?: InputMaybe<BlogBlocksFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type ProjectsBlocksHeroOverride = {
  __typename?: 'ProjectsBlocksHeroOverride';
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocksFullImage = {
  __typename?: 'ProjectsBlocksFullImage';
  image?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocksTextBlock = {
  __typename?: 'ProjectsBlocksTextBlock';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
};

export type ProjectsBlocksTwoColumn = {
  __typename?: 'ProjectsBlocksTwoColumn';
  leftContent?: Maybe<Scalars['JSON']['output']>;
  rightImage?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocksGallery = {
  __typename?: 'ProjectsBlocksGallery';
  images?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ProjectsBlocksQuote = {
  __typename?: 'ProjectsBlocksQuote';
  quoteText?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocksSpacer = {
  __typename?: 'ProjectsBlocksSpacer';
  size?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocks = ProjectsBlocksHeroOverride | ProjectsBlocksFullImage | ProjectsBlocksTextBlock | ProjectsBlocksTwoColumn | ProjectsBlocksGallery | ProjectsBlocksQuote | ProjectsBlocksSpacer;

export type Projects = Node & Document & {
  __typename?: 'Projects';
  title: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  client: Scalars['String']['output'];
  industry: Scalars['String']['output'];
  services: Array<Scalars['String']['output']>;
  excerpt: Scalars['String']['output'];
  heroImage: Scalars['String']['output'];
  published?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  blocks?: Maybe<Array<Maybe<ProjectsBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjectsBlocksHeroOverrideFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type ProjectsBlocksFullImageFilter = {
  image?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type ProjectsBlocksTextBlockFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ProjectsBlocksTwoColumnFilter = {
  leftContent?: InputMaybe<RichTextFilter>;
  rightImage?: InputMaybe<ImageFilter>;
};

export type ProjectsBlocksGalleryFilter = {
  images?: InputMaybe<ImageFilter>;
};

export type ProjectsBlocksQuoteFilter = {
  quoteText?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
};

export type ProjectsBlocksSpacerFilter = {
  size?: InputMaybe<StringFilter>;
};

export type ProjectsBlocksFilter = {
  heroOverride?: InputMaybe<ProjectsBlocksHeroOverrideFilter>;
  fullImage?: InputMaybe<ProjectsBlocksFullImageFilter>;
  textBlock?: InputMaybe<ProjectsBlocksTextBlockFilter>;
  twoColumn?: InputMaybe<ProjectsBlocksTwoColumnFilter>;
  gallery?: InputMaybe<ProjectsBlocksGalleryFilter>;
  quote?: InputMaybe<ProjectsBlocksQuoteFilter>;
  spacer?: InputMaybe<ProjectsBlocksSpacerFilter>;
};

export type ProjectsFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  client?: InputMaybe<StringFilter>;
  industry?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  published?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
  blocks?: InputMaybe<ProjectsBlocksFilter>;
};

export type ProjectsConnectionEdges = {
  __typename?: 'ProjectsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projects>;
};

export type ProjectsConnection = Connection & {
  __typename?: 'ProjectsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateServices: Services;
  createServices: Services;
  updateAbout: About;
  createAbout: About;
  updateTeam: Team;
  createTeam: Team;
  updateBlog: Blog;
  createBlog: Blog;
  updateProjects: Projects;
  createProjects: Projects;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationCreateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};

export type DocumentUpdateMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  services?: InputMaybe<ServicesMutation>;
  about?: InputMaybe<AboutMutation>;
  team?: InputMaybe<TeamMutation>;
  blog?: InputMaybe<BlogMutation>;
  projects?: InputMaybe<ProjectsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  services?: InputMaybe<ServicesMutation>;
  about?: InputMaybe<AboutMutation>;
  team?: InputMaybe<TeamMutation>;
  blog?: InputMaybe<BlogMutation>;
  projects?: InputMaybe<ProjectsMutation>;
};

export type HomepageHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageIntroMutation = {
  kicker?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomepageSelectedProjectsMutation = {
  project?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  hero?: InputMaybe<HomepageHeroMutation>;
  intro?: InputMaybe<HomepageIntroMutation>;
  selectedProjects?: InputMaybe<Array<InputMaybe<HomepageSelectedProjectsMutation>>>;
};

export type ServicesDisciplinesMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  statement?: InputMaybe<Scalars['String']['input']>;
  deliverables?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServicesProcessMutation = {
  step?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  disciplines?: InputMaybe<Array<InputMaybe<ServicesDisciplinesMutation>>>;
  process?: InputMaybe<Array<InputMaybe<ServicesProcessMutation>>>;
};

export type AboutPositioningMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  positioning?: InputMaybe<Array<InputMaybe<AboutPositioningMutation>>>;
};

export type TeamMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  shortBio?: InputMaybe<Scalars['String']['input']>;
  fullBio?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMutation = {
  members?: InputMaybe<Array<InputMaybe<TeamMembersMutation>>>;
};

export type BlogBlocksHeroOverrideMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type BlogBlocksFullImageMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type BlogBlocksTextBlockMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlogBlocksTwoColumnMutation = {
  leftContent?: InputMaybe<Scalars['JSON']['input']>;
  rightImage?: InputMaybe<Scalars['String']['input']>;
};

export type BlogBlocksGalleryMutation = {
  images?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BlogBlocksQuoteMutation = {
  quoteText?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
};

export type BlogBlocksSpacerMutation = {
  size?: InputMaybe<Scalars['String']['input']>;
};

export type BlogBlocksMutation = {
  heroOverride?: InputMaybe<BlogBlocksHeroOverrideMutation>;
  fullImage?: InputMaybe<BlogBlocksFullImageMutation>;
  textBlock?: InputMaybe<BlogBlocksTextBlockMutation>;
  twoColumn?: InputMaybe<BlogBlocksTwoColumnMutation>;
  gallery?: InputMaybe<BlogBlocksGalleryMutation>;
  quote?: InputMaybe<BlogBlocksQuoteMutation>;
  spacer?: InputMaybe<BlogBlocksSpacerMutation>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<BlogBlocksMutation>>>;
};

export type ProjectsBlocksHeroOverrideMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksFullImageMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksTextBlockMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ProjectsBlocksTwoColumnMutation = {
  leftContent?: InputMaybe<Scalars['JSON']['input']>;
  rightImage?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksGalleryMutation = {
  images?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ProjectsBlocksQuoteMutation = {
  quoteText?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksSpacerMutation = {
  size?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksMutation = {
  heroOverride?: InputMaybe<ProjectsBlocksHeroOverrideMutation>;
  fullImage?: InputMaybe<ProjectsBlocksFullImageMutation>;
  textBlock?: InputMaybe<ProjectsBlocksTextBlockMutation>;
  twoColumn?: InputMaybe<ProjectsBlocksTwoColumnMutation>;
  gallery?: InputMaybe<ProjectsBlocksGalleryMutation>;
  quote?: InputMaybe<ProjectsBlocksQuoteMutation>;
  spacer?: InputMaybe<ProjectsBlocksSpacerMutation>;
};

export type ProjectsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  client?: InputMaybe<Scalars['String']['input']>;
  industry?: InputMaybe<Scalars['String']['input']>;
  services?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<ProjectsBlocksMutation>>>;
};

export type HomepagePartsFragment = { __typename: 'Homepage', hero?: { __typename: 'HomepageHero', title?: string | null, subtitle?: string | null, videoUrl?: string | null } | null, intro?: { __typename: 'HomepageIntro', kicker?: string | null, title?: string | null, body?: any | null } | null, selectedProjects?: Array<{ __typename: 'HomepageSelectedProjects', project?: { __typename: 'Projects', title: string, slug?: string | null, client: string, industry: string, services: Array<string>, excerpt: string, heroImage: string, published?: boolean | null, order?: number | null, id: string, blocks?: Array<{ __typename: 'ProjectsBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'ProjectsBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'ProjectsBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'ProjectsBlocksGallery', images?: Array<string | null> | null } | { __typename: 'ProjectsBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'ProjectsBlocksSpacer', size?: string | null } | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null };

export type ServicesPartsFragment = { __typename: 'Services', headline?: string | null, intro?: string | null, disciplines?: Array<{ __typename: 'ServicesDisciplines', number?: string | null, label?: string | null, statement?: string | null, deliverables?: Array<string | null> | null } | null> | null, process?: Array<{ __typename: 'ServicesProcess', step?: string | null, title?: string | null, text?: string | null } | null> | null };

export type AboutPartsFragment = { __typename: 'About', headline?: string | null, intro?: string | null, positioning?: Array<{ __typename: 'AboutPositioning', title?: string | null, text?: string | null } | null> | null };

export type TeamPartsFragment = { __typename: 'Team', members?: Array<{ __typename: 'TeamMembers', name?: string | null, title?: string | null, image?: string | null, shortBio?: string | null, fullBio?: string | null } | null> | null };

export type BlogPartsFragment = { __typename: 'Blog', title: string, slug?: string | null, date: string, coverImage: string, excerpt: string, published?: boolean | null, order?: number | null, blocks?: Array<{ __typename: 'BlogBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'BlogBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'BlogBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'BlogBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'BlogBlocksGallery', images?: Array<string | null> | null } | { __typename: 'BlogBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'BlogBlocksSpacer', size?: string | null } | null> | null };

export type ProjectsPartsFragment = { __typename: 'Projects', title: string, slug?: string | null, client: string, industry: string, services: Array<string>, excerpt: string, heroImage: string, published?: boolean | null, order?: number | null, blocks?: Array<{ __typename: 'ProjectsBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'ProjectsBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'ProjectsBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'ProjectsBlocksGallery', images?: Array<string | null> | null } | { __typename: 'ProjectsBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'ProjectsBlocksSpacer', size?: string | null } | null> | null };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomepageHero', title?: string | null, subtitle?: string | null, videoUrl?: string | null } | null, intro?: { __typename: 'HomepageIntro', kicker?: string | null, title?: string | null, body?: any | null } | null, selectedProjects?: Array<{ __typename: 'HomepageSelectedProjects', project?: { __typename: 'Projects', title: string, slug?: string | null, client: string, industry: string, services: Array<string>, excerpt: string, heroImage: string, published?: boolean | null, order?: number | null, id: string, blocks?: Array<{ __typename: 'ProjectsBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'ProjectsBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'ProjectsBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'ProjectsBlocksGallery', images?: Array<string | null> | null } | { __typename: 'ProjectsBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'ProjectsBlocksSpacer', size?: string | null } | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomepageHero', title?: string | null, subtitle?: string | null, videoUrl?: string | null } | null, intro?: { __typename: 'HomepageIntro', kicker?: string | null, title?: string | null, body?: any | null } | null, selectedProjects?: Array<{ __typename: 'HomepageSelectedProjects', project?: { __typename: 'Projects', title: string, slug?: string | null, client: string, industry: string, services: Array<string>, excerpt: string, heroImage: string, published?: boolean | null, order?: number | null, id: string, blocks?: Array<{ __typename: 'ProjectsBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'ProjectsBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'ProjectsBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'ProjectsBlocksGallery', images?: Array<string | null> | null } | { __typename: 'ProjectsBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'ProjectsBlocksSpacer', size?: string | null } | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } | null } | null> | null } };

export type ServicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesQuery = { __typename?: 'Query', services: { __typename: 'Services', id: string, headline?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, disciplines?: Array<{ __typename: 'ServicesDisciplines', number?: string | null, label?: string | null, statement?: string | null, deliverables?: Array<string | null> | null } | null> | null, process?: Array<{ __typename: 'ServicesProcess', step?: string | null, title?: string | null, text?: string | null } | null> | null } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
}>;


export type ServicesConnectionQuery = { __typename?: 'Query', servicesConnection: { __typename?: 'ServicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesConnectionEdges', cursor: string, node?: { __typename: 'Services', id: string, headline?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, disciplines?: Array<{ __typename: 'ServicesDisciplines', number?: string | null, label?: string | null, statement?: string | null, deliverables?: Array<string | null> | null } | null> | null, process?: Array<{ __typename: 'ServicesProcess', step?: string | null, title?: string | null, text?: string | null } | null> | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, headline?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, positioning?: Array<{ __typename: 'AboutPositioning', title?: string | null, text?: string | null } | null> | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, headline?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, positioning?: Array<{ __typename: 'AboutPositioning', title?: string | null, text?: string | null } | null> | null } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'TeamMembers', name?: string | null, title?: string | null, image?: string | null, shortBio?: string | null, fullBio?: string | null } | null> | null } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'TeamMembers', name?: string | null, title?: string | null, image?: string | null, shortBio?: string | null, fullBio?: string | null } | null> | null } | null } | null> | null } };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, slug?: string | null, date: string, coverImage: string, excerpt: string, published?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'BlogBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'BlogBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'BlogBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'BlogBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'BlogBlocksGallery', images?: Array<string | null> | null } | { __typename: 'BlogBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'BlogBlocksSpacer', size?: string | null } | null> | null } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, slug?: string | null, date: string, coverImage: string, excerpt: string, published?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'BlogBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'BlogBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'BlogBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'BlogBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'BlogBlocksGallery', images?: Array<string | null> | null } | { __typename: 'BlogBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'BlogBlocksSpacer', size?: string | null } | null> | null } | null } | null> | null } };

export type ProjectsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectsQuery = { __typename?: 'Query', projects: { __typename: 'Projects', id: string, title: string, slug?: string | null, client: string, industry: string, services: Array<string>, excerpt: string, heroImage: string, published?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'ProjectsBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'ProjectsBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'ProjectsBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'ProjectsBlocksGallery', images?: Array<string | null> | null } | { __typename: 'ProjectsBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'ProjectsBlocksSpacer', size?: string | null } | null> | null } };

export type ProjectsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
}>;


export type ProjectsConnectionQuery = { __typename?: 'Query', projectsConnection: { __typename?: 'ProjectsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectsConnectionEdges', cursor: string, node?: { __typename: 'Projects', id: string, title: string, slug?: string | null, client: string, industry: string, services: Array<string>, excerpt: string, heroImage: string, published?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'ProjectsBlocksHeroOverride', title?: string | null, image?: string | null } | { __typename: 'ProjectsBlocksFullImage', image?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksTextBlock', heading?: string | null, body?: any | null } | { __typename: 'ProjectsBlocksTwoColumn', leftContent?: any | null, rightImage?: string | null } | { __typename: 'ProjectsBlocksGallery', images?: Array<string | null> | null } | { __typename: 'ProjectsBlocksQuote', quoteText?: string | null, author?: string | null } | { __typename: 'ProjectsBlocksSpacer', size?: string | null } | null> | null } | null } | null> | null } };

export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  hero {
    __typename
    title
    subtitle
    videoUrl
  }
  intro {
    __typename
    kicker
    title
    body
  }
  selectedProjects {
    __typename
    project {
      ... on Projects {
        __typename
        title
        slug
        client
        industry
        services
        excerpt
        heroImage
        published
        order
        blocks {
          __typename
          ... on ProjectsBlocksHeroOverride {
            title
            image
          }
          ... on ProjectsBlocksFullImage {
            image
            caption
          }
          ... on ProjectsBlocksTextBlock {
            heading
            body
          }
          ... on ProjectsBlocksTwoColumn {
            leftContent
            rightImage
          }
          ... on ProjectsBlocksGallery {
            images
          }
          ... on ProjectsBlocksQuote {
            quoteText
            author
          }
          ... on ProjectsBlocksSpacer {
            size
          }
        }
      }
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
    }
  }
}
    `;
export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  headline
  intro
  disciplines {
    __typename
    number
    label
    statement
    deliverables
  }
  process {
    __typename
    step
    title
    text
  }
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  headline
  intro
  positioning {
    __typename
    title
    text
  }
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  members {
    __typename
    name
    title
    image
    shortBio
    fullBio
  }
}
    `;
export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  slug
  date
  coverImage
  excerpt
  published
  order
  blocks {
    __typename
    ... on BlogBlocksHeroOverride {
      title
      image
    }
    ... on BlogBlocksFullImage {
      image
      caption
    }
    ... on BlogBlocksTextBlock {
      heading
      body
    }
    ... on BlogBlocksTwoColumn {
      leftContent
      rightImage
    }
    ... on BlogBlocksGallery {
      images
    }
    ... on BlogBlocksQuote {
      quoteText
      author
    }
    ... on BlogBlocksSpacer {
      size
    }
  }
}
    `;
export const ProjectsPartsFragmentDoc = gql`
    fragment ProjectsParts on Projects {
  __typename
  title
  slug
  client
  industry
  services
  excerpt
  heroImage
  published
  order
  blocks {
    __typename
    ... on ProjectsBlocksHeroOverride {
      title
      image
    }
    ... on ProjectsBlocksFullImage {
      image
      caption
    }
    ... on ProjectsBlocksTextBlock {
      heading
      body
    }
    ... on ProjectsBlocksTwoColumn {
      leftContent
      rightImage
    }
    ... on ProjectsBlocksGallery {
      images
    }
    ... on ProjectsBlocksQuote {
      quoteText
      author
    }
    ... on ProjectsBlocksSpacer {
      size
    }
  }
}
    `;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const ProjectsDocument = gql`
    query projects($relativePath: String!) {
  projects(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectsParts
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const ProjectsConnectionDocument = gql`
    query projectsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectsFilter) {
  projectsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectsParts
      }
    }
  }
}
    ${ProjectsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    projects(variables: ProjectsQueryVariables, options?: C): Promise<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}> {
        return requester<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}, ProjectsQueryVariables>(ProjectsDocument, variables, options);
      },
    projectsConnection(variables?: ProjectsConnectionQueryVariables, options?: C): Promise<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}, ProjectsConnectionQueryVariables>(ProjectsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  